In [2]:
import pandas as pd

df = pd.read_csv("data/healthcare_dataset.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [10]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

In [ ]:
print(df["Name"].duplicated().sum())

5508
<bound method DataFrame.isnull of                     Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]>
Name                  49992
Age                      77
Gender                    2
Blood Type                8
Medical Condition         6
Date of Admission      1827
Doctor                40341
Hospital              39876
Insurance Provider        5
Billing Amount        50000
Room Number             400
Admission Type            3
Discharge Date         1856
Medication                5
Test Results              3
dtype: int64

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [16]:
print(df.nunique())

Name                  49992
Age                      77
Gender                    2
Blood Type                8
Medical Condition         6
Date of Admission      1827
Doctor                40341
Hospital              39876
Insurance Provider        5
Billing Amount        50000
Room Number             400
Admission Type            3
Discharge Date         1856
Medication                5
Test Results              3
dtype: int64

In [19]:
print(df.isnull().sum())

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [3]:
df.columns = df.columns.str.strip().str.lower().str.replace(r"[^\w]+", "_", regex=True)

In [12]:
df["date_of_admission"] = pd.to_datetime(df["date_of_admission"])
df["discharge_date"] = pd.to_datetime(df["discharge_date"])
df["length_of_stay"] = (df["discharge_date"] - df["date_of_admission"]).dt.days
df.to_csv("healthcare_dataset.csv", index=False)

In [13]:
df.columns

Index(['name', 'age', 'gender', 'blood_type', 'medical_condition',
       'date_of_admission', 'doctor', 'hospital', 'insurance_provider',
       'billing_amount', 'room_number', 'admission_type', 'discharge_date',
       'medication', 'test_results', 'length_of_stay'],
      dtype='object')

In [8]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:1234@localhost:3306/healthcare")

In [14]:
df.to_sql("healthcare_dataset", con=engine, if_exists="replace", index=False)

55500